### ISSUE TITLE
how to connect with database

### ISSUE THREAD

**Issue by Sriharshajasti123** [JatinSadhwani02/Login-and-Registration-System-in-Flask#1]

**Comment by JatinSadhwani02** [comment]
Open the xxamp or wampp server then create database with name app_assign then click on import then import app_assign.sql file and click on go... Now Dataset is connected with xxamp or wamp . Now you can use

**Comment by Sriharshajasti123** [comment]
> Open the xxamp or wampp server then create database with name app_assign then click on import then import app_assign.sql file and click on go... Now Dataset is connected with xxamp or wamp . Now you can use

It's working, thanks for responding

**Comment by JatinSadhwani02** [comment]
Welcome ♥️
